//
//  File.swift
//  solaRecipes
//
//  Created by Ahmed Moussa on 9/13/16.
//  Copyright © 2016 Ahmed Moussa. All rights reserved.
//
//
//  Recipes.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.3
//

import Foundation
import UIKit
import AWSDynamoDB

class recipe {
    
    var picures = [UIImage]()
    var recie = DBRecipe()
    
    init(id: String, name: String, insts: String, desc: String, temp: NSNumber, dur: NSNumber, creatorFBID: String, creatorName: String, numOfPics: Int){
        recie?._id = id
        recie?._name = name
        recie?._instructions = insts
        recie?._description = desc
        recie?._temperature = temp
        recie?._duration = dur
        recie?._creatorFBID = creatorFBID
        recie?._creatorName = creatorName
        recie?._numberOfPictures = numOfPics as NSNumber
    }
    init(recip: DBRecipe){
        recie = recip
    }
    

}

