//
//  Recipes.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.3
//

import Foundation
import UIKit
import AWSDynamoDB

class Recipes: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _description: String?
    var _duration: NSNumber?
    var _name: String?
    var _temperature: String?
    
    class func dynamoDBTableName() -> String {

        return "solarovenrecipes-mobilehub-1674615168-Recipes"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_userId" : "userId",
               "_description" : "description",
               "_duration" : "duration",
               "_name" : "name",
               "_temperature" : "temperature",
        ]
    }
}
